User.create!([
  {email: "g@gurke.de", password: "12345678", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2015-02-25 12:52:55", last_sign_in_at: "2015-02-24 13:35:52", current_sign_in_ip: "192.168.178.25", last_sign_in_ip: "127.0.0.1", first_name: "Günther", last_name: "Gurke"}
])
Basket.create!([
  {notice: "", amount: "53.94", document: nil, user_id: 1, payment_id: 2, vendor_id: 5, purchase_date: "2015-04-01"},
  {notice: "GEZ nervt", amount: "53.94", document: nil, user_id: 1, payment_id: 1, vendor_id: 12, purchase_date: "2015-07-01"},
  {notice: "", amount: "53.94", document: nil, user_id: 1, payment_id: 2, vendor_id: 5, purchase_date: "2015-01-01"},
  {notice: "", amount: "150.0", document: nil, user_id: 1, payment_id: 4, vendor_id: 2, purchase_date: "2015-04-09"},
  {notice: nil, amount: "25.0", document: nil, user_id: 1, payment_id: 3, vendor_id: 4, purchase_date: "2015-01-30"},
  {notice: nil, amount: "15.44", document: nil, user_id: 1, payment_id: 3, vendor_id: 1, purchase_date: "2015-02-01"},
  {notice: nil, amount: "4.5", document: nil, user_id: 1, payment_id: 1, vendor_id: 8, purchase_date: "2015-01-15"},
  {notice: nil, amount: "50.0", document: "6F72675F626F6E5F71312E6A7067", user_id: 1, payment_id: 3, vendor_id: 11, purchase_date: "2015-01-20"},
  {notice: "Semesterbeitrag", amount: "234.75", document: nil, user_id: 1, payment_id: 3, vendor_id: 8, purchase_date: "2015-01-31"},
  {notice: nil, amount: "25.9", document: nil, user_id: 1, payment_id: 2, vendor_id: 6, purchase_date: "2015-02-25"},
  {notice: "Jeden Donnerstag Pizza bei Bogazici", amount: "5.2", document: nil, user_id: 1, payment_id: 1, vendor_id: 10, purchase_date: "2015-02-05"}
])
Category.create!([
  {name: "Gehalt", notice: "Gehalt + Sonderzahlungen von ZEB", active: true, income: true, user_id: 1, glyphicon_id: 170},
  {name: "Geschenke", notice: "Geschenke von Freunden und der Familie", active: true, income: true, user_id: 1, glyphicon_id: 271},
  {name: "Haushalt/Lebensmittel", notice: "Für Artikel des alltäglichen Bedarfs", active: true, income: false, user_id: 1, glyphicon_id: 74},
  {name: "Rückerstattungen", notice: "Rückerstattungen von Spesen und Reisekosten", active: true, income: true, user_id: 1, glyphicon_id: 160},
  {name: "Restaurantbesuche", notice: "", active: true, income: false, user_id: 1, glyphicon_id: 121},
  {name: "Sprit", notice: "Kategorie für Spritkosten (Eigenbedarf)", active: true, income: false, user_id: 1, glyphicon_id: 78},
  {name: "Fixe Unterhaltskosten", notice: "Kategorie für Strom, Internet, Telefon, Gas, Wasser, etc.", active: true, income: false, user_id: 1, glyphicon_id: 290},
  {name: "Party", notice: "Kategorie für alles Ausgaben die tief in der Nacht getätigt werden", active: true, income: false, user_id: 1, glyphicon_id: 595},
  {name: "Studium", notice: "Studiumskosten (Semesterbeitrag, Büromaterial, etc.)", active: true, income: false, user_id: 1, glyphicon_id: 372},
  {name: "Sport", notice: "Mitgliedsbeiträge und Ausrüstung", active: true, income: false, user_id: 1, glyphicon_id: 501},
  {name: "Bekleidung", notice: "Klamotten & Co.", active: true, income: false, user_id: 1, glyphicon_id: 189}
])

Item.create!([
  {basket_id: nil, category_id: 1, article_id: nil, user_id: 1, name: "Bafög", quantity: nil, price: "500.0", notice: "", income: true, period: 1, launch: "2015-02-02", finish: "2015-02-02", period_id: nil},
  {basket_id: nil, category_id: 4, article_id: nil, user_id: 1, name: "Bafög", quantity: nil, price: "500.0", notice: "", income: true, period: 1, launch: "2015-05-01", finish: "2015-05-04", period_id: nil},
  {basket_id: nil, category_id: 1, article_id: nil, user_id: 1, name: "Bafög", quantity: nil, price: "500.0", notice: "", income: true, period: 1, launch: "2015-07-01", finish: "2015-07-02", period_id: nil},
  {basket_id: 10, category_id: 7, article_id: nil, user_id: 1, name: "GEZ", quantity: "1.0", price: "53.94", notice: "GEZ nervt", income: false, period: nil, launch: nil, finish: nil, period_id: nil},
  {basket_id: 11, category_id: 7, article_id: nil, user_id: 1, name: "GEZ", quantity: "1.0", price: "53.94", notice: "", income: false, period: nil, launch: nil, finish: nil, period_id: nil},
  {basket_id: 12, category_id: 7, article_id: nil, user_id: 1, name: "GEZ", quantity: "1.0", price: "53.94", notice: "", income: false, period: nil, launch: nil, finish: nil, period_id: nil},
  {basket_id: 13, category_id: 8, article_id: nil, user_id: 1, name: "Urlaub", quantity: "1.0", price: "150.0", notice: "Anzahlung", income: false, period: nil, launch: nil, finish: nil, period_id: nil},
  {basket_id: nil, category_id: 4, article_id: nil, user_id: 1, name: "Bafög", quantity: nil, price: "500.0", notice: "Bafög", income: true, period: 1, launch: "2015-08-01", finish: "2015-08-05", period_id: nil},
  {basket_id: nil, category_id: 2, article_id: nil, user_id: 1, name: "Bafög", quantity: nil, price: "500.0", notice: "", income: true, period: 1, launch: "2015-04-01", finish: "2015-04-02", period_id: nil},
  {basket_id: nil, category_id: 4, article_id: nil, user_id: 1, name: "Bafög", quantity: nil, price: "500.0", notice: "", income: true, period: 1, launch: "2015-03-03", finish: "2015-03-04", period_id: nil},
  {basket_id: nil, category_id: 2, article_id: nil, user_id: 1, name: "Bafög", quantity: nil, price: "500.0", notice: "", income: true, period: 1, launch: "2015-06-01", finish: "2015-06-02", period_id: nil},
  {basket_id: nil, category_id: 4, article_id: nil, user_id: 1, name: "Mittagessen 30.11.2014", quantity: nil, price: "9.6", notice: "", income: true, period: nil, launch: "2014-12-30", finish: "2014-12-30", period_id: 1},
  {basket_id: nil, category_id: 4, article_id: nil, user_id: 1, name: "Spesenrückerstattung", quantity: nil, price: "89.5", notice: "War ein guter Workshop von P3 zum Thema BigData", income: true, period: nil, launch: "2015-02-16", finish: "2015-02-16", period_id: 1},
  {basket_id: nil, category_id: 1, article_id: nil, user_id: 1, name: "monatliches Gehalt", quantity: nil, price: "450.0", notice: "Gehalt ZEB", income: true, period: nil, launch: "2014-09-30", finish: "2015-09-30", period_id: 3},
  {basket_id: nil, category_id: 2, article_id: nil, user_id: 1, name: "Oma Weihnachten", quantity: nil, price: "50.0", notice: "Omi ist die Beste!", income: true, period: nil, launch: "2014-12-24", finish: "2014-12-24", period_id: 1},
  {basket_id: nil, category_id: 1, article_id: nil, user_id: 1, name: "Bafög", quantity: nil, price: "500.0", notice: "", income: true, period: nil, launch: "2014-01-04", finish: "2015-08-01", period_id: 2},
  {basket_id: nil, category_id: 2, article_id: nil, user_id: 1, name: "Onkel Tom Zeugnis", quantity: nil, price: "25.0", notice: "Nächstes Mal mehr anstrengen!", income: true, period: nil, launch: "2015-01-16", finish: "2015-01-16", period_id: 1},
  {basket_id: 7, category_id: 5, article_id: nil, user_id: 1, name: "Mittagessen", quantity: "1.0", price: "5.2", notice: "Aktionstag Pizza", income: false, period: nil, launch: "2015-02-05", finish: "2015-02-05", period_id: nil},
  {basket_id: 5, category_id: 9, article_id: nil, user_id: 1, name: "Semesterbeitrag SS2014", quantity: "1.0", price: "234.75", notice: "", income: false, period: nil, launch: "2015-01-31", finish: "2015-01-31", period_id: nil},
  {basket_id: 4, category_id: 6, article_id: nil, user_id: 1, name: "Sprit", quantity: "1.0", price: "50.0", notice: "Sprit für Januar", income: false, period: nil, launch: "2015-01-20", finish: "2015-01-20", period_id: nil},
  {basket_id: 3, category_id: 9, article_id: nil, user_id: 1, name: "Klausurskript Software Entwicklung II", quantity: "1.0", price: "4.5", notice: "", income: false, period: nil, launch: "2015-01-15", finish: "2015-01-15", period_id: nil},
  {basket_id: 2, category_id: 3, article_id: nil, user_id: 1, name: "Quark", quantity: "0.59", price: "3.0", notice: "", income: false, period: nil, launch: "2015-02-01", finish: "2015-02-01", period_id: nil},
  {basket_id: 2, category_id: 3, article_id: nil, user_id: 1, name: "Coca Cola", quantity: "1.25", price: "6.0", notice: "", income: false, period: nil, launch: "2015-02-01", finish: "2015-02-01", period_id: nil},
  {basket_id: 2, category_id: 9, article_id: nil, user_id: 1, name: "Ringblock DIN A4", quantity: "0.89", price: "2.0", notice: "", income: false, period: nil, launch: "2015-02-01", finish: "2015-02-01", period_id: nil},
  {basket_id: 2, category_id: 3, article_id: nil, user_id: 1, name: "Milch", quantity: "0.65", price: "3.0", notice: "", income: false, period: nil, launch: "2015-02-01", finish: "2015-02-01", period_id: nil},
  {basket_id: 2, category_id: 3, article_id: nil, user_id: 1, name: "Lachgummi", quantity: "0.99", price: "1.0", notice: "", income: false, period: nil, launch: "2015-02-01", finish: "2015-02-01", period_id: nil},
  {basket_id: 2, category_id: 3, article_id: nil, user_id: 1, name: "Sahne", quantity: "0.35", price: "2.0", notice: "", income: false, period: nil, launch: "2015-02-01", finish: "2015-02-01", period_id: nil},
  {basket_id: 2, category_id: 3, article_id: nil, user_id: 1, name: "WC Reiniger", quantity: "0.75", price: "1.0", notice: "", income: false, period: nil, launch: "2015-02-01", finish: "2015-02-01", period_id: nil},
  {basket_id: 1, category_id: 7, article_id: nil, user_id: 1, name: "Internet L", quantity: "1.0", price: "25.0", notice: "", income: false, period: nil, launch: "2015-01-30", finish: "2015-01-30", period_id: nil},
  {basket_id: 6, category_id: 3, article_id: nil, user_id: 1, name: "Spagetti Carbonara", quantity: "3.0", price: "0.65", notice: "", income: false, period: nil, launch: "2015-02-25", finish: "2015-02-25", period_id: nil},
  {basket_id: 6, category_id: 3, article_id: nil, user_id: 1, name: "Seife", quantity: "1.0", price: "0.7", notice: "", income: false, period: nil, launch: "2015-02-25", finish: "2015-02-25", period_id: nil},
  {basket_id: 6, category_id: 3, article_id: nil, user_id: 1, name: "Baguette", quantity: "2.0", price: "1.0", notice: "", income: false, period: nil, launch: "2015-02-25", finish: "2015-02-25", period_id: nil},
  {basket_id: 6, category_id: 3, article_id: nil, user_id: 1, name: "Joghurt", quantity: "1.0", price: "4.0", notice: "", income: false, period: nil, launch: "2015-02-25", finish: "2015-02-25", period_id: nil},
  {basket_id: 6, category_id: 3, article_id: nil, user_id: 1, name: "ct Dezember", quantity: "1.0", price: "4.5", notice: "", income: false, period: nil, launch: "2015-02-25", finish: "2015-02-25", period_id: nil},
  {basket_id: 6, category_id: 10, article_id: nil, user_id: 1, name: "Tischtennisball", quantity: "1.0", price: "2.5", notice: "", income: false, period: nil, launch: "2015-02-25", finish: "2015-02-25", period_id: nil},
  {basket_id: 6, category_id: 9, article_id: nil, user_id: 1, name: "10x Kugelschreiber", quantity: "1.0", price: "1.2", notice: "", income: false, period: nil, launch: "2015-02-25", finish: "2015-02-25", period_id: nil},
  {basket_id: 6, category_id: 8, article_id: nil, user_id: 1, name: "Apfelkorn", quantity: "1.0", price: "6.0", notice: "", income: false, period: nil, launch: "2015-02-25", finish: "2015-02-25", period_id: nil},
  {basket_id: 6, category_id: 3, article_id: nil, user_id: 1, name: "Cracker", quantity: "1.0", price: "2.45", notice: "", income: false, period: nil, launch: "2015-02-25", finish: "2015-02-25", period_id: nil},
  {basket_id: 6, category_id: 8, article_id: nil, user_id: 1, name: "Veltins Six Pack", quantity: "1.0", price: "4.0", notice: "", income: false, period: nil, launch: "2015-02-25", finish: "2015-02-25", period_id: nil}
])

Payment.create!([
  {user_id: 1, number: "0", bic: "0", active: true, name: "Barzahlung"},
  {user_id: 1, number: "999999999", bic: "26550105", active: true, name: "Visa"},
  {user_id: 1, number: "AL90208110080000001039531801", bic: "20811008", active: true, name: "Girokonto"},
  {user_id: 1, number: "g@gurke.de", bic: "1", active: true, name: "Paypal"}
])
Period.create!([
  {name: "Einmalig", value: 1},
  {name: "Wöchentlich", value: 7},
  {name: "Monatlich", value: 30},
  {name: "Jährlich", value: 365}
])
Vendor.create!([
  {name: "ALDI", logo: "aldi-logo.png", user_id: 1},
  {name: "Amazon", logo: "500px-Amazon_com_logo_svg.png", user_id: 1},
  {name: "Vermieter", logo: "pik_vermieter.jpg", user_id: 1},
  {name: "Telekom", logo: "1000px-Deutsche_Telekom-Logo.svg.png", user_id: 1},
  {name: "Stadtwerke Münster", logo: "Stadtwerke_M_nster_Logo.svg.png", user_id: 1},
  {name: "EDEKA", logo: "Edeka-logo.jpg", user_id: 1},
  {name: "Lotto", logo: "lotto_mit_kugeln.jpeg", user_id: 1},
  {name: "Fachhochschule Münster", logo: "Logo_FH_Muenster_cmyk.svg.png", user_id: 1},
  {name: "Zalando", logo: "Zalando_Logo.png", user_id: 1},
  {name: "Bogazici Schnellrestaurant", logo: "bogazici.jpg", user_id: 1},
  {name: "Q1 Tankstelle", logo: "org_220px-Q1_Tankstellenvertrieb_logo.svg.png", user_id: 1},
  {name: "Mensa", logo: "org_mensa.png", user_id: 1}
])


connection = ActiveRecord::Base.connection()
connection.execute("
update vendors
set logo='aldi-logo.png'
where Id = 1;


update vendors
set logo='500px-Amazon_com_logo_svg.png'
where Id = 2;


update vendors
set logo='pik_vermieter.jpg'
where Id = 3;

update vendors
set logo='1000px-Deutsche_Telekom-Logo.svg.png'
where Id = 4;

update vendors
set logo='Stadtwerke_M_nster_Logo.svg.png'
where Id = 5;

update vendors
set logo='Edeka-logo.jpg'
where Id = 6;

update vendors
set logo='lotto_mit_kugeln.jpeg'
where Id = 7;


update vendors
set logo='Logo_FH_Muenster_cmyk.svg.png'
where Id = 8;

update vendors
set logo='Zalando_Logo.png'
where Id = 9;

update vendors
set logo='bogazici.jpg'
where Id = 10;

update vendors
set logo='org_220px-Q1_Tankstellenvertrieb_logo.svg.png'
where Id = 11;

update vendors
set logo='org_mensa.png'
where Id = 12;")



Glyphicon.create!([
                      {name: "fa-address-book"},
                      {name: "fa-address-book-alt"},
                      {name: "fa-adjust"},
                      {name: "fa-adjust-alt"},
                      {name: "fa-adn"},
                      {name: "fa-adult"},
                      {name: "fa-align-center"},
                      {name: "fa-align-justify"},
                      {name: "fa-align-left"},
                      {name: "fa-align-right"},
                      {name: "fa-ambulance"},
                      {name: "fa-anchor"},
                      {name: "fa-android"},
                      {name: "fa-angle-double-down"},
                      {name: "fa-angle-double-left"},
                      {name: "fa-angle-double-right"},
                      {name: "fa-angle-double-up"},
                      {name: "fa-angle-down"},
                      {name: "fa-angle-left"},
                      {name: "fa-angle-right"},
                      {name: "fa-angle-up"},
                      {name: "fa-apple"},
                      {name: "fa-archive"},
                      {name: "fa-arrow-circle-down"},
                      {name: "fa-arrow-circle-left"},
                      {name: "fa-arrow-circle-o-down"},
                      {name: "fa-arrow-circle-o-left"},
                      {name: "fa-arrow-circle-o-right"},
                      {name: "fa-arrow-circle-o-up"},
                      {name: "fa-arrow-circle-right"},
                      {name: "fa-arrow-circle-up"},
                      {name: "fa-arrow-down"},
                      {name: "fa-arrow-left"},
                      {name: "fa-arrow-right"},
                      {name: "fa-arrows"},
                      {name: "fa-arrows-alt"},
                      {name: "fa-arrows-h"},
                      {name: "fa-arrows-v"},
                      {name: "fa-arrow-up"},
                      {name: "fa-asl"},
                      {name: "fa-asterisk"},
                      {name: "fa-backward"},
                      {name: "fa-ban"},
                      {name: "fa-ban-circle"},
                      {name: "fa-bar-chart-o"},
                      {name: "fa-barcode"},
                      {name: "fa-bars"},
                      {name: "fa-beer"},
                      {name: "fa-behance"},
                      {name: "fa-bell"},
                      {name: "fa-bell-o"},
                      {name: "fa-bitbucket"},
                      {name: "fa-bitbucket-square"},
                      {name: "fa-bitcoin"},
                      {name: "fa-blind"},
                      {name: "fa-blogger"},
                      {name: "fa-bold"},
                      {name: "fa-bolt"},
                      {name: "fa-book"},
                      {name: "fa-bookmark"},
                      {name: "fa-bookmark-empty"},
                      {name: "fa-bookmark-o"},
                      {name: "fa-braille"},
                      {name: "fa-briefcase"},
                      {name: "fa-broom"},
                      {name: "fa-brush"},
                      {name: "fa-btc"},
                      {name: "fa-bug"},
                      {name: "fa-building-o"},
                      {name: "fa-bulb"},
                      {name: "fa-bullhorn"},
                      {name: "fa-bullseye"},
                      {name: "fa-calendar"},
                      {name: "fa-calendar-o"},
                      {name: "fa-calendar-sign"},
                      {name: "fa-camera"},
                      {name: "fa-camera-retro"},
                      {name: "fa-car"},
                      {name: "fa-caret-down"},
                      {name: "fa-caret-left"},
                      {name: "fa-caret-right"},
                      {name: "fa-caret-square-o-down"},
                      {name: "fa-caret-square-o-left"},
                      {name: "fa-caret-square-o-right"},
                      {name: "fa-caret-square-o-up"},
                      {name: "fa-caret-up"},
                      {name: "fa-cc"},
                      {name: "fa-certificate"},
                      {name: "fa-chain"},
                      {name: "fa-chain-broken"},
                      {name: "fa-check"},
                      {name: "fa-check-circle"},
                      {name: "fa-check-circle-o"},
                      {name: "fa-check-empty"},
                      {name: "fa-check-square"},
                      {name: "fa-check-square-o"},
                      {name: "fa-chevron-circle-down"},
                      {name: "fa-chevron-circle-left"},
                      {name: "fa-chevron-circle-right"},
                      {name: "fa-chevron-circle-up"},
                      {name: "fa-chevron-down"},
                      {name: "fa-chevron-left"},
                      {name: "fa-chevron-right"},
                      {name: "fa-chevron-up"},
                      {name: "fa-child"},
                      {name: "fa-circle"},
                      {name: "fa-circle-arrow-down"},
                      {name: "fa-circle-arrow-left"},
                      {name: "fa-circle-arrow-right"},
                      {name: "fa-circle-arrow-up"},
                      {name: "fa-circle-o"},
                      {name: "fa-clipboard"},
                      {name: "fa-clock-o"},
                      {name: "fa-cloud"},
                      {name: "fa-cloud-alt"},
                      {name: "fa-cloud-download"},
                      {name: "fa-cloud-upload"},
                      {name: "fa-cny"},
                      {name: "fa-code"},
                      {name: "fa-code-fork"},
                      {name: "fa-coffee"},
                      {name: "fa-cog"},
                      {name: "fa-cog-alt"},
                      {name: "fa-cogs"},
                      {name: "fa-collapse-down"},
                      {name: "fa-collapse-up"},
                      {name: "fa-columns"},
                      {name: "fa-comment"},
                      {name: "fa-comment-alt"},
                      {name: "fa-comment-o"},
                      {name: "fa-comments"},
                      {name: "fa-comments-o"},
                      {name: "fa-compass"},
                      {name: "fa-compass-alt"},
                      {name: "fa-compress"},
                      {name: "fa-compressed"},
                      {name: "fa-copy"},
                      {name: "fa-copyright-mark"},
                      {name: "fa-credit-card"},
                      {name: "fa-crop"},
                      {name: "fa-crosshairs"},
                      {name: "fa-css"},
                      {name: "fa-css3"},
                      {name: "fa-cut"},
                      {name: "fa-cutlery"},
                      {name: "fa-dashboard"},
                      {name: "fa-dedent"},
                      {name: "fa-delicious"},
                      {name: "fa-desktop"},
                      {name: "fa-deviantart"},
                      {name: "fa-digg"},
                      {name: "fa-dollar"},
                      {name: "fa-dot-circle-o"},
                      {name: "fa-download"},
                      {name: "fa-download-alt"},
                      {name: "fa-dribbble"},
                      {name: "fa-dropbox"},
                      {name: "fa-earphone"},
                      {name: "fa-edit"},
                      {name: "fa-eject"},
                      {name: "fa-ellipsis-h"},
                      {name: "fa-ellipsis-v"},
                      {name: "fa-envelope"},
                      {name: "fa-envelope-alt"},
                      {name: "fa-envelope-o"},
                      {name: "fa-eraser"},
                      {name: "fa-error"},
                      {name: "fa-error-alt"},
                      {name: "fa-eur"},
                      {name: "fa-euro"},
                      {name: "fa-exchange"},
                      {name: "fa-exclamation"},
                      {name: "fa-exclamation-circle"},
                      {name: "fa-exclamation-sign"},
                      {name: "fa-exclamation-triangle"},
                      {name: "fa-expand"},
                      {name: "fa-export"},
                      {name: "fa-external-link"},
                      {name: "fa-external-link-square"},
                      {name: "fa-eye"},
                      {name: "fa-eye-close"},
                      {name: "fa-eye-open"},
                      {name: "fa-eye-slash"},
                      {name: "fa-facebook"},
                      {name: "fa-facebook-square"},
                      {name: "fa-facetime-video"},
                      {name: "fa-fast-backward"},
                      {name: "fa-fast-forward"},
                      {name: "fa-female"},
                      {name: "fa-fighter-jet"},
                      {name: "fa-file"},
                      {name: "fa-file-alt"},
                      {name: "fa-file-edit"},
                      {name: "fa-file-edit-alt"},
                      {name: "fa-file-new"},
                      {name: "fa-file-new-alt"},
                      {name: "fa-file-o"},
                      {name: "fa-files-o"},
                      {name: "fa-file-text"},
                      {name: "fa-file-text-o"},
                      {name: "fa-film"},
                      {name: "fa-filter"},
                      {name: "fa-fire"},
                      {name: "fa-fire-extinguisher"},
                      {name: "fa-flag"},
                      {name: "fa-flag-alt"},
                      {name: "fa-flag-checkered"},
                      {name: "fa-flag-o"},
                      {name: "fa-flash"},
                      {name: "fa-flask"},
                      {name: "fa-flickr"},
                      {name: "fa-floppy-disk"},
                      {name: "fa-floppy-o"},
                      {name: "fa-floppy-open"},
                      {name: "fa-floppy-remove"},
                      {name: "fa-floppy-save"},
                      {name: "fa-floppy-saved"},
                      {name: "fa-folder"},
                      {name: "fa-folder-close"},
                      {name: "fa-folder-o"},
                      {name: "fa-folder-open"},
                      {name: "fa-folder-open-o"},
                      {name: "fa-folder-sign"},
                      {name: "fa-font"},
                      {name: "fa-fontsize"},
                      {name: "fa-fork"},
                      {name: "fa-forward"},
                      {name: "fa-forward-alt"},
                      {name: "fa-foursquare"},
                      {name: "fa-friendfeed"},
                      {name: "fa-friendfeed-rect"},
                      {name: "fa-frown-o"},
                      {name: "fa-fullscreen"},
                      {name: "fa-gamepad"},
                      {name: "fa-gavel"},
                      {name: "fa-gbp"},
                      {name: "fa-gear"},
                      {name: "fa-gears"},
                      {name: "fa-gift"},
                      {name: "fa-github"},
                      {name: "fa-github-alt"},
                      {name: "fa-github-square"},
                      {name: "fa-github-text"},
                      {name: "fa-gittip"},
                      {name: "fa-glass"},
                      {name: "fa-glasses"},
                      {name: "fa-globe"},
                      {name: "fa-globe-alt"},
                      {name: "fa-googleplus"},
                      {name: "fa-google-plus"},
                      {name: "fa-google-plus-square"},
                      {name: "fa-graph"},
                      {name: "fa-graph-alt"},
                      {name: "fa-group"},
                      {name: "fa-group-alt"},
                      {name: "fa-guidedog"},
                      {name: "fa-hand-down"},
                      {name: "fa-hand-left"},
                      {name: "fa-hand-o-down"},
                      {name: "fa-hand-o-left"},
                      {name: "fa-hand-o-right"},
                      {name: "fa-hand-o-up"},
                      {name: "fa-hand-right"},
                      {name: "fa-hand-up"},
                      {name: "fa-hdd"},
                      {name: "fa-hdd-o"},
                      {name: "fa-hd-video"},
                      {name: "fa-header"},
                      {name: "fa-headphones"},
                      {name: "fa-hearing-impaired"},
                      {name: "fa-heart"},
                      {name: "fa-heart-alt"},
                      {name: "fa-heart-empty"},
                      {name: "fa-heart-o"},
                      {name: "fa-home"},
                      {name: "fa-home-alt"},
                      {name: "fa-hospital-o"},
                      {name: "fa-hourglass"},
                      {name: "fa-h-square"},
                      {name: "fa-html5"},
                      {name: "fa-idea"},
                      {name: "fa-idea-alt"},
                      {name: "fa-import"},
                      {name: "fa-inbox"},
                      {name: "fa-inbox-alt"},
                      {name: "fa-inbox-box"},
                      {name: "fa-indent"},
                      {name: "fa-indent-left"},
                      {name: "fa-indent-right"},
                      {name: "fa-info"},
                      {name: "fa-info-circle"},
                      {name: "fa-info-sign"},
                      {name: "fa-inr"},
                      {name: "fa-instagram"},
                      {name: "fa-iphone-home"},
                      {name: "fa-italic"},
                      {name: "fa-jpy"},
                      {name: "fa-key"},
                      {name: "fa-keyboard-o"},
                      {name: "fa-krw"},
                      {name: "fa-laptop"},
                      {name: "fa-laptop-alt"},
                      {name: "fa-lastfm"},
                      {name: "fa-leaf"},
                      {name: "fa-legal"},
                      {name: "fa-lemon-o"},
                      {name: "fa-level-down"},
                      {name: "fa-level-up"},
                      {name: "fa-lightbulb-o"},
                      {name: "fa-lines"},
                      {name: "fa-link"},
                      {name: "fa-linkedin"},
                      {name: "fa-linkedin-square"},
                      {name: "fa-linux"},
                      {name: "fa-list"},
                      {name: "fa-list-alt"},
                      {name: "fa-list-ol"},
                      {name: "fa-list-ul"},
                      {name: "fa-livejournal"},
                      {name: "fa-location-arrow"},
                      {name: "fa-lock"},
                      {name: "fa-lock-alt"},
                      {name: "fa-log-in"},
                      {name: "fa-log-out"},
                      {name: "fa-long-arrow-down"},
                      {name: "fa-long-arrow-left"},
                      {name: "fa-long-arrow-right"},
                      {name: "fa-long-arrow-up"},
                      {name: "fa-magic"},
                      {name: "fa-magnet"},
                      {name: "fa-mail-forward"},
                      {name: "fa-mail-reply"},
                      {name: "fa-mail-reply-all"},
                      {name: "fa-male"},
                      {name: "fa-map-marker"},
                      {name: "fa-map-marker-alt"},
                      {name: "fa-maxcdn"},
                      {name: "fa-medkit"},
                      {name: "fa-meh-o"},
                      {name: "fa-mic"},
                      {name: "fa-mic-alt"},
                      {name: "fa-microphone"},
                      {name: "fa-microphone-slash"},
                      {name: "fa-minus-circle"},
                      {name: "fa-minus-sign"},
                      {name: "fa-minus-square"},
                      {name: "fa-minus-square-o"},
                      {name: "fa-mobile"},
                      {name: "fa-mobile-phone"},
                      {name: "fa-money"},
                      {name: "fa-moon-o"},
                      {name: "fa-move"},
                      {name: "fa-music"},
                      {name: "fa-myspace"},
                      {name: "fa-network"},
                      {name: "fa-new-window"},
                      {name: "fa-off"},
                      {name: "fa-ok"},
                      {name: "fa-ok-circle"},
                      {name: "fa-ok-sign"},
                      {name: "fa-open"},
                      {name: "fa-opensource"},
                      {name: "fa-outdent"},
                      {name: "fa-pagelines"},
                      {name: "fa-paperclip"},
                      {name: "fa-paper-clip"},
                      {name: "fa-paper-clip-alt"},
                      {name: "fa-paste"},
                      {name: "fa-path"},
                      {name: "fa-pause"},
                      {name: "fa-pause-alt"},
                      {name: "fa-pencil"},
                      {name: "fa-pencil-alt"},
                      {name: "fa-pencil-square"},
                      {name: "fa-pencil-square-o"},
                      {name: "fa-person"},
                      {name: "fa-phone"},
                      {name: "fa-phone-alt"},
                      {name: "fa-phone-square"},
                      {name: "fa-photo"},
                      {name: "fa-photo-alt"},
                      {name: "fa-picasa"},
                      {name: "fa-picture"},
                      {name: "fa-picture-o"},
                      {name: "fa-pinterest"},
                      {name: "fa-pinterest-square"},
                      {name: "fa-plane"},
                      {name: "fa-play"},
                      {name: "fa-play-alt"},
                      {name: "fa-play-circle"},
                      {name: "fa-play-circle-o"},
                      {name: "fa-plus"},
                      {name: "fa-plus-circle"},
                      {name: "fa-plus-sign"},
                      {name: "fa-plus-square"},
                      {name: "fa-plus-square-o"},
                      {name: "fa-podcast"},
                      {name: "fa-power-off"},
                      {name: "fa-print"},
                      {name: "fa-pushpin"},
                      {name: "fa-puzzle"},
                      {name: "fa-puzzle-piece"},
                      {name: "fa-qrcode"},
                      {name: "fa-question"},
                      {name: "fa-question-circle"},
                      {name: "fa-question-sign"},
                      {name: "fa-quote-left"},
                      {name: "fa-quote-right"},
                      {name: "fa-quotes"},
                      {name: "fa-quotes-alt"},
                      {name: "fa-random"},
                      {name: "fa-record"},
                      {name: "fa-reddit"},
                      {name: "fa-refresh"},
                      {name: "fa-registration-mark"},
                      {name: "fa-remove"},
                      {name: "fa-remove-circle"},
                      {name: "fa-remove-sign"},
                      {name: "fa-renren"},
                      {name: "fa-repeat"},
                      {name: "fa-repeat-alt"},
                      {name: "fa-reply"},
                      {name: "fa-reply-all"},
                      {name: "fa-resize-full"},
                      {name: "fa-resize-horizontal"},
                      {name: "fa-resize-small"},
                      {name: "fa-resize-vertical"},
                      {name: "fa-return-key"},
                      {name: "fa-retweet"},
                      {name: "fa-reverse-alt"},
                      {name: "fa-rmb"},
                      {name: "fa-road"},
                      {name: "fa-rocket"},
                      {name: "fa-rotate-left"},
                      {name: "fa-rotate-right"},
                      {name: "fa-rouble"},
                      {name: "fa-rss"},
                      {name: "fa-rss-square"},
                      {name: "fa-rub"},
                      {name: "fa-ruble"},
                      {name: "fa-rupee"},
                      {name: "fa-save"},
                      {name: "fa-saved"},
                      {name: "fa-scissors"},
                      {name: "fa-screen"},
                      {name: "fa-screen-alt"},
                      {name: "fa-screenshot"},
                      {name: "fa-sd-video"},
                      {name: "fa-search"},
                      {name: "fa-search-alt"},
                      {name: "fa-search-minus"},
                      {name: "fa-search-plus"},
                      {name: "fa-send"},
                      {name: "fa-share"},
                      {name: "fa-share-alt"},
                      {name: "fa-share-square"},
                      {name: "fa-share-square-o"},
                      {name: "fa-shield"},
                      {name: "fa-shopping-cart"},
                      {name: "fa-shopping-cart-sign"},
                      {name: "fa-signal"},
                      {name: "fa-sign-in"},
                      {name: "fa-sign-out"},
                      {name: "fa-sitemap"},
                      {name: "fa-skype"},
                      {name: "fa-slideshare"},
                      {name: "fa-smile-o"},
                      {name: "fa-smiley"},
                      {name: "fa-smiley-alt"},
                      {name: "fa-sort"},
                      {name: "fa-sort-alpha-asc"},
                      {name: "fa-sort-alpha-desc"},
                      {name: "fa-sort-amount-asc"},
                      {name: "fa-sort-amount-desc"},
                      {name: "fa-sort-asc"},
                      {name: "fa-sort-by-alphabet"},
                      {name: "fa-sort-by-alphabet-alt"},
                      {name: "fa-sort-by-attributes"},
                      {name: "fa-sort-by-attributes-alt"},
                      {name: "fa-sort-by-order"},
                      {name: "fa-sort-by-order-alt"},
                      {name: "fa-sort-desc"},
                      {name: "fa-sort-down"},
                      {name: "fa-sort-numeric-asc"},
                      {name: "fa-sort-numeric-desc"},
                      {name: "fa-sort-up"},
                      {name: "fa-sound-5-1"},
                      {name: "fa-sound-6-1"},
                      {name: "fa-sound-7-1"},
                      {name: "fa-soundcloud"},
                      {name: "fa-sound-dolby"},
                      {name: "fa-sound-stereo"},
                      {name: "fa-speaker"},
                      {name: "fa-spinner"},
                      {name: "fa-spotify"},
                      {name: "fa-square"},
                      {name: "fa-square-o"},
                      {name: "fa-stack-exchange"},
                      {name: "fa-stackoverflow"},
                      {name: "fa-stack-overflow"},
                      {name: "fa-star"},
                      {name: "fa-star-alt"},
                      {name: "fa-star-empty"},
                      {name: "fa-star-half"},
                      {name: "fa-star-half-empty"},
                      {name: "fa-star-half-full"},
                      {name: "fa-star-half-o"},
                      {name: "fa-star-o"},
                      {name: "fa-stats"},
                      {name: "fa-step-backward"},
                      {name: "fa-step-forward"},
                      {name: "fa-stethoscope"},
                      {name: "fa-stop"},
                      {name: "fa-stop-alt"},
                      {name: "fa-strikethrough"},
                      {name: "fa-stumbleupon"},
                      {name: "fa-subscript"},
                      {name: "fa-subtitles"},
                      {name: "fa-suitcase"},
                      {name: "fa-sun-o"},
                      {name: "fa-superscript"},
                      {name: "fa-table"},
                      {name: "fa-tablet"},
                      {name: "fa-tachometer"},
                      {name: "fa-tag"},
                      {name: "fa-tags"},
                      {name: "fa-tasks"},
                      {name: "fa-terminal"},
                      {name: "fa-text-height"},
                      {name: "fa-text-width"},
                      {name: "fa-th"},
                      {name: "fa-th-large"},
                      {name: "fa-th-list"},
                      {name: "fa-thumbs-down"},
                      {name: "fa-thumbs-o-down"},
                      {name: "fa-thumbs-o-up"},
                      {name: "fa-thumbs-up"},
                      {name: "fa-thumb-tack"},
                      {name: "fa-ticket"},
                      {name: "fa-time"},
                      {name: "fa-time-alt"},
                      {name: "fa-times"},
                      {name: "fa-times-circle"},
                      {name: "fa-times-circle-o"},
                      {name: "fa-tint"},
                      {name: "fa-toggle-down"},
                      {name: "fa-toggle-left"},
                      {name: "fa-toggle-right"},
                      {name: "fa-toggle-up"},
                      {name: "fa-torso"},
                      {name: "fa-tower"},
                      {name: "fa-transfer"},
                      {name: "fa-trash"},
                      {name: "fa-trash-alt"},
                      {name: "fa-trash-o"},
                      {name: "fa-tree-conifer"},
                      {name: "fa-tree-deciduous"},
                      {name: "fa-trello"},
                      {name: "fa-trophy"},
                      {name: "fa-truck"},
                      {name: "fa-try"},
                      {name: "fa-tumblr"},
                      {name: "fa-tumblr-square"},
                      {name: "fa-turkish-lira"},
                      {name: "fa-twitter"},
                      {name: "fa-twitter-square"},
                      {name: "fa-umbrella"},
                      {name: "fa-unchecked"},
                      {name: "fa-underline"},
                      {name: "fa-undo"},
                      {name: "fa-universal-access"},
                      {name: "fa-unlink"},
                      {name: "fa-unlock"},
                      {name: "fa-unlock-alt"},
                      {name: "fa-unsorted"},
                      {name: "fa-upload"},
                      {name: "fa-usd"},
                      {name: "fa-user"},
                      {name: "fa-user-md"},
                      {name: "fa-users"},
                      {name: "fa-viadeo"},
                      {name: "fa-video"},
                      {name: "fa-video-alt"},
                      {name: "fa-video-camera"},
                      {name: "fa-video-chat"},
                      {name: "fa-view-mode"},
                      {name: "fa-vimeo"},
                      {name: "fa-vimeo-square"},
                      {name: "fa-vk"},
                      {name: "fa-vkontakte"},
                      {name: "fa-volume-down"},
                      {name: "fa-volume-off"},
                      {name: "fa-volume-up"},
                      {name: "fa-w3c"},
                      {name: "fa-warning"},
                      {name: "fa-warning-sign"},
                      {name: "fa-website"},
                      {name: "fa-website-alt"},
                      {name: "fa-weibo"},
                      {name: "fa-wheelchair"},
                      {name: "fa-windows"},
                      {name: "fa-won"},
                      {name: "fa-wordpress"},
                      {name: "fa-wrench"},
                      {name: "fa-wrench-alt"},
                      {name: "fa-xing"},
                      {name: "fa-xing-square"},
                      {name: "fa-yen"},
                      {name: "fa-youtube"},
                      {name: "fa-youtube-play"},
                      {name: "fa-youtube-square"},
                      {name: "fa-zoom-in"},
                      {name: "fa-zoom-out"}
                  ])
